services:
  web:
    container_name: Project-web
    image: node:22.9.0
    working_dir: /app/web
    volumes:
      - './web:/app/web'
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']